"""        TASK 1 
##Use any data structure of your choice to organize the following information
Your names
Your slack username
Your email
Your hobby
Your countries
Your discipline
Your preferred programming language
"""
# Storing personal information in a dictionary
choice_datastru = {
    "Name":"Arpit Sharma",
    "Slack Username":"Arpit",
    "Email":"8920arpit@gmail.com",
    "Hobby":"Gaming and cooking",
    "Country":"India",
    "Discipline":"Bioinformatics",
    "Preferred Programming Language":"Python"
}
print(choice_datastru) # Printing the entire dictionary
Name= choice_datastru["Name"]
print(Name)   # Accessing and printing a specific value (Name)
